### ISSUE TITLE
[Bug]: Knockback miscalculation.

### ISSUE THREAD

**Issue by Skidamek** [FamroFexl/Circumnavigate#11]
### Describe the Bug

when you gently touch other entity from other side of the world / behind the border entity gets knocked back to you instead of further from you

### Mod version(s) affected

1.0.2

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

### To Reproduce (If applicable)

1. Go to the world border
2. Spawn some entity
3. Go to the other side of border
4. Gently touch the entity

**Comment by FamroFexl** [comment]
It is much more apparent if you try hitting the entity from the other side of the border. 

I assume this is technically because the player across the border is "behind" the other player, albeit several dozen chunks away in a large wrapped world.

**Comment by Skidamek** [comment]
Yes it's kind of obvious but funny bug
