### ISSUE TITLE
[Bug]: minecarts can't cross borders

### ISSUE THREAD

**Issue by Skidamek** [FamroFexl/Circumnavigate#13]
### Describe the Bug

minecarts are just getting stuck on borders

### Mod version(s) affected

0.3

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

**Comment by FamroFexl** [comment]
This is an issue with rails specifically. 

1. If you slime bounce a minecart across the border, it doesn't have any issues getting across.
2. If you run a minecart from a straight rail to a slanted rail across the border, it gets stuck going up and down. The same is true for straight to straight rail.
3. If you run a minecart down a slanted rail to a slanted rail, it will be rejected backwards up a 3 block rail slant.

**Comment by Skidamek** [comment]
This is so awesome, now you can make never ending track
