### ISSUE TITLE
[Bug]: Cannot place block against border

### ISSUE THREAD

**Issue by Skidamek** [FamroFexl/Circumnavigate#14]
### Describe the Bug

While you can place block on the opposite side of border, you can't place blocks inside the current chunk, supported by blocks from opposite side of the border

### Mod version(s) affected

0.3

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

### To Reproduce (If applicable)

1. Go to border
2. Try to place any block against different block from opposite side of border

**Comment by FamroFexl** [comment]
This also occurs on the other side of the border as well, and it is not border-specific (directional). Using a ladder as the last block in the border chunk, when placing a block against it on both sides, it fails to place in both cases.

**Comment by FamroFexl** [comment]
Apparently, my offsets which allowed the blocks to be placed also messed up minecart placements and interaction.

**Comment by FamroFexl** [comment]
Yep, now if I am activating a lever from the side, it will just place the item in my hand instead. Still broken.
