### ISSUE TITLE
[Bug]: Pistons can't grab blocks from opposite side of the border

### ISSUE THREAD

**Issue by Skidamek** [FamroFexl/Circumnavigate#20]
### Describe the Bug

While pistons can place block on the other side of the border, they (sticky piston) can't take those blocks back

### Mod version(s) affected

all

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.20.4

**Comment by FamroFexl** [comment]
Can now grab blocks and push blocks. Flying machines can now travel across borders!
