### ISSUE TITLE
[Bug]: Chunks render break on too high render distance 

### ISSUE THREAD

**Issue by Skidamek** [FamroFexl/Circumnavigate#23]
### Describe the Bug

It looks just like server would not send those chunks to client since they are loaded with level of 31 under f3 + g and also other player may stand in the same place and see these chunks normally

### Mod version(s) affected

probably 0.4 and git

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.21.1

### To Reproduce (If applicable)

Fly in one direction long enough

**Comment by FamroFexl** [comment]
I cannot reproduce this issue. On dedicated and LAN, they all work properly.

**Comment by Skidamek** [comment]
Only reproducible when player have too high render distance in proportion to world
