### ISSUE TITLE
[Bug]: Game crashes on load.

### ISSUE THREAD

**Issue by RileyClement1** [FamroFexl/Circumnavigate#26]
### Describe the Bug

If you try to start minecraft with the mod, It crashes. From the crash report it seems like the mixins aren't able to inject properly.

### Mod version(s) affected

0.4

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.21.1

### Other mods used

Fabric API

### To Reproduce (If applicable)

Run minecraft with the mod.

### Additional Information

I've also had two friends try to run the mod as well and they had the same error.

Crash report: [latest.log](https://github.com/user-attachments/files/17769568/latest.log)

I think these are the important lines:

```

Suppressed: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Failed to validate sugar @Local(name = "entity2") class_1297 on method wrapDelta(Lnet/minecraft/class_1282;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V from mixin circumnavigate.mixins.json:entityHandle.LivingEntityMixin from mod circumnavigate in target method net/minecraft/class_1309::method_5643(Lnet/minecraft/class_1282;F)Z at instruction InjectionNode[MethodInsn [INVOKEVIRTUAL] net/minecraft/class_1309::method_6005(DDD)V]`

Caused by: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Unable to find matching local!
```

**Comment by FamroFexl** [comment]
Try this version (uncompress)
[circumnavigate-0.4.1+1.21.1-fabric.jar.zip](https://github.com/user-attachments/files/17769942/circumnavigate-0.4.1%2B1.21.1-fabric.jar.zip)

**Comment by RileyClement1** [comment]
That seems to have fixed the issue with the LivingEntitiesMixin class but now the same error is occurring in FishingHookMixin. I assume whatever you did will work again on FishingHookMixin.

```
Suppressed: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Failed to validate sugar @Local(name = "entity2") LocalRef on method wrapDelta(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)V from mixin circumnavigate.mixins.json:entityHandle.entities.FishingHookMixin from mod circumnavigate in target method net/minecraft/class_1536::method_6954(Lnet/minecraft/class_1297;)V at instruction InjectionNode[MethodInsn [INVOKEVIRTUAL] net/minecraft/class_1297::method_18799(Lnet/minecraft/class_243;)V]
```

Crash report: [latest.log](https://github.com/user-attachments/files/17770144/latest.log)

**Comment by FamroFexl** [comment]
> That seems to have fixed the issue with the LivingEntitiesMixin class but now the same error is occurring in FishingHookMixin. I assume whatever you did will work again on FishingHookMixin.
> 
> ```
> Suppressed: com.llamalad7.mixinextras.sugar.impl.SugarApplicationException: Failed to validate sugar @Local(name = "entity2") LocalRef on method wrapDelta(Lnet/minecraft/class_1297;Lnet/minecraft/class_243;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)V from mixin circumnavigate.mixins.json:entityHandle.entities.FishingHookMixin from mod circumnavigate in target method net/minecraft/class_1536::method_6954(Lnet/minecraft/class_1297;)V at instruction InjectionNode[MethodInsn [INVOKEVIRTUAL] net/minecraft/class_1297::method_18799(Lnet/minecraft/class_243;)V]
> ```
> 
> Crash report: [latest.log](https://github.com/user-attachments/files/17770144/latest.log)

Yep, just found a bunch more issues about it. Working on it.

**Comment by FamroFexl** [comment]
Here you go. https://github.com/FamroFexl/Circumnavigate/releases/tag/0.4.1
