### ISSUE TITLE
[Bug]: Entities do not wrap correctly

### ISSUE THREAD

**Issue by iijj22gg** [FamroFexl/Circumnavigate#32]
### Describe the Bug

Entities do not properly collide with wrapped blocks until the center of the entity crosses

### Mod version(s) affected

0.4.1

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.21.1

### Other mods used

Like, 80+ for compatability testing, though they are irrelevant in this case

### To Reproduce (If applicable)

Push a mob over a border
![image](https://github.com/user-attachments/assets/ecff2fa9-6d4f-403e-b27d-f8f70e127c86)

### Additional Information

Entities can either be pushed into walls, or will fall before they even step off the block they are standing on

**Comment by FamroFexl** [comment]
A simple way to visualize this issue is to enclose an animal pen with one wall as the border. Entity cramming will force animals into the border.
![2024-12-03_12 10 26](https://github.com/user-attachments/assets/3f958b23-60f2-4ed3-9460-6cb1e921259d)

**Comment by FamroFexl** [comment]
If you find any entities jumping at the border wall, that's probably just a pathfinding issue.
