### ISSUE TITLE
[Bug]: Parts of block entity models dont render after going wrapped distance

### ISSUE THREAD

**Issue by Skidamek** [FamroFexl/Circumnavigate#35]
### Describe the Bug

title

### Mod version(s) affected

0.4.1 - git

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.21.1

### To Reproduce (If applicable)

- Place or find any block entity
- See it rendering
- Go full wrapped distance of your world so you return to the same place again but in wrapped chunks
- Can't see block entity models, only hitbox renders

### Additional Information

![2024-12-09_08 06 25](https://github.com/user-attachments/assets/917c67aa-3360-4149-83c4-24e2b88110bf)
![2024-12-09_08 08 02](https://github.com/user-attachments/assets/a3c027ed-2165-4fb2-8b16-c04e62017905)
![2024-12-09_08 08 34](https://github.com/user-attachments/assets/459335ed-b70e-4b97-a3a8-67d291b0da70)
![2024-12-09_08 08 45](https://github.com/user-attachments/assets/cccfb163-3c64-4281-83c2-1a5930905bf6)

**Comment by FamroFexl** [comment]
Just a wild guess here, but this might be related to minecraft's optimization that stops rendering distant tile entities.

**Comment by Skidamek** [comment]
But why? Sure it's wrapped chunk but client doesn't know that, for client it should be like any other normal chunk. 

Does block entities have server sidely coordinates assigned inside a chunk data?

**Comment by Skidamek** [comment]
Interestingly enough seems like it does actually, check out `ClientboundLevelChunkPacketData` class. It holds `blockEntitiesData` object which has coordinates of each and every block entity in the chunk. Looks like another packet we need to transform is `ClientboundLevelChunkWithLightPacket` which sends that data. I think we need to swap unwrapped coordinates of block entities to wrapped coordinates.

**Comment by FamroFexl** [comment]
Apparently, it pays to implement things properly, such as not keeping the transformations of `ClientboundLevelChunkWithLightPacket` in `PlayerChunkSenderMixin` and `ClientboundLevelChunkWithLightPacketMixin` when they could easily be transferred to the `PacketTransformer`. This caused the `LevelChunk` argument of `ClientboundLevelChunkPacketData` to use the wrong `ChunkPos` and screw up the blockEntities.
