### ISSUE TITLE
[Bug]: Some (Block)Entity interactions are a bit broken

### ISSUE THREAD

**Issue by Skidamek** [FamroFexl/Circumnavigate#36]
### Describe the Bug

e.g. going to sleep in a bed on wrapped chunks teleports you to unwrapped chunks breaking chunk loading

### Mod version(s) affected

0.4.1 - git

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.21.1

### To Reproduce (If applicable)

1. Go to your worlds' wrapped chunks
2. Place a bed
3. Make/wait for night
4. Go sleep
5. See chunk loading breaking and you coordinates swap to the unwrapped

### Additional Information

https://youtu.be/Gy0kINKE5Hg

**Comment by FamroFexl** [comment]
~~Looks like `ClientboundPlayerPositionPacket` isn't transforming properly...~~ The player position received from the client has been changed by the client somehow. Somehow, the client has knowledge of it's actual position...

**Comment by FamroFexl** [comment]
Yep, the client decides to move to that position, and the server follows the client's lead. Somehow, the client has access to it's position. I've already checked that it wasn't because of an unwrapped packet, namely `ClientboundBlockEntityDataPacket`.

**Comment by FamroFexl** [comment]
> I've already checked that it wasn't because of an unwrapped packet, namely `ClientboundBlockEntityDataPacket`.

Which I have now added in 2f6c008

**Comment by FamroFexl** [comment]
It was because of an unwrapped packet, `ClientboundSetEntityDataPacket`. The reason I didn't catch it before is because I didn't realize client & server synched values could contain `Positions`.
