### ISSUE TITLE
[Feature Request]: Actual limited worlds?

### ISSUE THREAD

**Issue by FR00TP3NCH** [FamroFexl/Circumnavigate#8]
### Suggestion

It would be cool if this mod had a feature where worlds didn't wrap around and kind of generated into an ocean like in the Legacy Console Editions of Minecraft (xbox 360 edition for example)

**Comment by FamroFexl** [comment]
I'm not sure what you mean. This mod does make the world limited and will eventually have seamless world generation.

**Comment by Skidamek** [comment]
I think they meant that world wouldn't be finite, but after the border there would be only ocean but I think it's not really the point of this mod

**Comment by FamroFexl** [comment]
Island world gen and a world border would satisfy that request.

**Comment by Skidamek** [comment]
Yeah @FR00TP3NCH [this mod](https://modrinth.com/datapack/one-survival-island) is probably what you are looking for
